<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PublishSingleFile>true</PublishSingleFile>
		<PackAsTool>True</PackAsTool>
		<SelfContained>true</SelfContained>
		<PublishReadyToRun>true</PublishReadyToRun>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<!--
		<ApplicationIcon>Assets\HourgalssIcon4.ico</ApplicationIcon>
		-->
		<ApplicationIcon>Assets\timespan-logo.ico</ApplicationIcon>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<OutputType>WinExe</OutputType>
		<DefineConstants>$(DefineConstants);PUBLISHED</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.VsixColorCompiler" Version="17.11.35325.10" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\DatabaseUtil\DatabaseUtil.csproj" />
		<ProjectReference Include="..\Timespan.Database\Timespan.Database.csproj" />
		<ProjectReference Include="..\Timespan.PDF\Timespan.PDF.csproj" />
		<ProjectReference Include="..\Timespan.Gui\Timespan.Gui.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets\**\*" />
	</ItemGroup>
</Project>