// <auto-generated />
using Timespan.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Timespan.Database.Migrations
{
    [DbContext(typeof(HourglassDbContext))]
    [Migration("20250825072045_1.0")]
    partial class _10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Timespan.Database.Models.Project", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Timespan.Database.Types.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("finish")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ownerid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("projectName")
                        .HasColumnType("TEXT");

                    b.Property<long>("start")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ticketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ownerid");

                    b.HasIndex("projectName");

                    b.HasIndex("ticketId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Timespan.Database.Models.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Ownerid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ownerid");

                    b.HasIndex("ProjectName");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Timespan.Database.Models.Worker", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("Timespan.Database.Types.Task", b =>
                {
                    b.HasOne("Timespan.Database.Models.Worker", "owner")
                        .WithMany()
                        .HasForeignKey("ownerid");

                    b.HasOne("Timespan.Database.Models.Project", "project")
                        .WithMany()
                        .HasForeignKey("projectName");

                    b.HasOne("Timespan.Database.Models.Ticket", "ticket")
                        .WithMany()
                        .HasForeignKey("ticketId");

                    b.Navigation("owner");

                    b.Navigation("project");

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("Timespan.Database.Models.Ticket", b =>
                {
                    b.HasOne("Timespan.Database.Models.Worker", "Owner")
                        .WithMany()
                        .HasForeignKey("Ownerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timespan.Database.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectName");

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
