// <auto-generated />
using Timespan.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Timespan.Database.Migrations
{
    [DbContext(typeof(HourglassDbContext))]
    [Migration("20251016193337_1.3")]
    partial class _13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Timespan.Database.Models.Project", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Timespan.Database.Models.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("displayColorBlue")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("displayColorGreen")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("displayColorRed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("finish")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ownerid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("projectName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("running")
                        .HasColumnType("INTEGER");

                    b.Property<long>("start")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ticketid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ownerid");

                    b.HasIndex("projectName");

                    b.HasIndex("ticketid");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Timespan.Database.Models.Ticket", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ownerid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("projectName")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("ownerid");

                    b.HasIndex("projectName");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Timespan.Database.Models.Worker", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("Timespan.Database.Models.Task", b =>
                {
                    b.HasOne("Timespan.Database.Models.Worker", "owner")
                        .WithMany()
                        .HasForeignKey("ownerid");

                    b.HasOne("Timespan.Database.Models.Project", "project")
                        .WithMany()
                        .HasForeignKey("projectName");

                    b.HasOne("Timespan.Database.Models.Ticket", "ticket")
                        .WithMany()
                        .HasForeignKey("ticketid");

                    b.Navigation("owner");

                    b.Navigation("project");

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("Timespan.Database.Models.Ticket", b =>
                {
                    b.HasOne("Timespan.Database.Models.Worker", "owner")
                        .WithMany()
                        .HasForeignKey("ownerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timespan.Database.Models.Project", "project")
                        .WithMany()
                        .HasForeignKey("projectName");

                    b.Navigation("owner");

                    b.Navigation("project");
                });
#pragma warning restore 612, 618
        }
    }
}
