namespace Timespan.GUI.Generators.Attributes;

using System;
using System.Collections.Generic;
using System.Text;



/// <summary>
/// Turns a group of <see cref="PropertyModel"/> records that share the same class
/// into a complete partial-class source file.
/// </summary>
internal static class CodeEmitter {
	public static string Emit(
		string? @namespace,
		string className,
		string[] containingTypeNames,
		IEnumerable<PropertyModel> properties) {
		var sb = new StringBuilder();

		// ── Header ────────────────────────────────────────────────────────────
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using Avalonia;");
		sb.AppendLine("using Avalonia.Data;");
		sb.AppendLine();

		// ── Namespace ─────────────────────────────────────────────────────────
		bool hasNamespace = !string.IsNullOrEmpty(@namespace);
		if (hasNamespace) {
			sb.AppendLine($"namespace {@namespace}");
			sb.AppendLine("{");
		}

		// ── Containing (outer) types ──────────────────────────────────────────
		int indent = hasNamespace ? 1 : 0;
		foreach (var outerType in containingTypeNames) {
			sb.AppendLine($"{Indent(indent)}public partial class {outerType}");
			sb.AppendLine($"{Indent(indent)}{{");
			indent++;
		}

		// ── The actual class ──────────────────────────────────────────────────
		sb.AppendLine($"{Indent(indent)}public partial class {className}");
		sb.AppendLine($"{Indent(indent)}{{");
		indent++;

		foreach (var prop in properties) {
			EmitProperty(sb, prop, indent);
			sb.AppendLine();
		}

		// Close the class
		indent--;
		sb.AppendLine($"{Indent(indent)}}}");

		// Close containing types
		foreach (var _ in containingTypeNames) {
			indent--;
			sb.AppendLine($"{Indent(indent)}}}");
		}

		// Close namespace
		if (hasNamespace)
			sb.AppendLine("}");

		return sb.ToString();
	}

	// ─────────────────────────────────────────────────────────────────────────

	private static void EmitProperty(StringBuilder sb, PropertyModel p, int indent) {
		string propName = NamingHelpers.ToPascalCase(p.FieldName);
		string staticName = NamingHelpers.ToStaticFieldName(propName);
		string type = p.FieldType;
		string owner = p.ClassName;

		// Default value argument – fall back to default(T) when not specified
		string defaultArg = p.DefaultValueSource ?? $"default({type})";

		string I = Indent(indent);

		// ── Static DirectProperty field ───────────────────────────────────────
		sb.AppendLine($"{I}public static readonly DirectProperty<{owner}, {type}> {staticName} =");
		sb.AppendLine($"{I}    AvaloniaProperty.RegisterDirect<{owner}, {type}>(");
		sb.AppendLine($"{I}        nameof({propName}),");
		sb.AppendLine($"{I}        control => control.{propName},");
		sb.AppendLine($"{I}        (control, value) => control.{propName} = value,");
		sb.AppendLine($"{I}        {defaultArg},");
		sb.AppendLine($"{I}        BindingMode.TwoWay);");
		sb.AppendLine();

		// ── Public CLR property ───────────────────────────────────────────────
		sb.AppendLine($"{I}public {type} {propName}");
		sb.AppendLine($"{I}{{");
		sb.AppendLine($"{I}    get => {p.FieldName};");
		sb.AppendLine($"{I}    set => SetAndRaise({staticName}, ref {p.FieldName}, value);");
		sb.AppendLine($"{I}}}");
	}

	private static string Indent(int level) => new string(' ', level * 4);
}