namespace Timespan.GUI.Generators.Attributes.StyledPropertyAttribute;

/// <summary>
/// Contains the source text of the attribute that is injected into every compilation
/// that references this generator. This way users don't need a separate NuGet package
/// for the attribute – it arrives automatically.
/// </summary>
internal static class AttributeSource {
	public const string AttributeFullName =
		"Timespan.GUI.Generators.Attributes.BasicDirectPropertyAttribute`1";

	public const string HintName = "BasicDirectPropertyAttribute.g.cs";

	public const string Source = """
        // <auto-generated/>
        #nullable enable
        using System;

        namespace AvaloniaDirectPropertyGenerator
        {
            /// <summary>
            /// Mark a private backing field with this attribute to have the Avalonia
            /// DirectProperty boilerplate generated automatically in a partial class.
            /// </summary>
            /// <typeparam name="TOwner">The AvaloniaObject that owns this property.</typeparam>
            [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
            public sealed class BasicDirectPropertyAttribute<TOwner> : Attribute { }
        }
        """;
}