<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Library</OutputType>
	<TargetFramework>net10.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<SelfContained>true</SelfContained>
	<PublishSingleFile>true</PublishSingleFile>
	<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
	<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.0.3" />
		<PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.3" />
		<PackageReference Include="Microsoft.VisualStudio.VsixColorCompiler" Version="17.11.35325.10" />
		<PackageReference Include="ReactiveUI.Avalonia" Version="12.0.1" />
		<PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.9" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.15" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Xaml.Behaviors.Interactions" Version="12.0.0" />
	</ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\HourGlass.PDF\Hourglass.PDF.csproj" />
	  <ProjectReference Include="..\HourGlass.Database\Hourglass.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Compile Update="Properties\Resources.Designer.cs">
	  <DesignTime>True</DesignTime>
	  <AutoGen>True</AutoGen>
	  <DependentUpon>Resources.resx</DependentUpon>
	</Compile>
	<Compile Update="Views\Components\CustomButton.axaml.cs">
	  <DependentUpon>CustomButton.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Components\DocumentPreviewer.axaml.cs">
	  <DependentUpon>DocumentPreviewer.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Components\GraphModeButtonIcons\MonthGraphModeButtonIcon.axaml.cs">
	  <DependentUpon>MonthGraphModeButtonIcon.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Components\GraphModeButtonIcons\WeekGraphModeButtonIcon.axaml.cs">
	  <DependentUpon>WeekGraphModeButtonIcon.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Components\GraphModeButtonIcons\DayGraphModeButtonIcon.axaml.cs">
	  <DependentUpon>DayGraphModeButtonIcon.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Components\GraphPanels\MonthGraphPanelView.axaml.cs">
	  <DependentUpon>MonthGraphPanelView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Components\GraphPanels\GraphPanelViewBase.axaml.cs">
	  <DependentUpon>GraphPanelViewBase.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Components\GraphPanels\WeekGraphPanelView.axaml.cs">
	  <DependentUpon>WeekGraphPanelView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Components\GraphPanels\DayGraphPanelView.axaml.cs">
	  <DependentUpon>DayGraphPanelView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\SettingsPages\GeneralSubSettingsPageView.axaml.cs">
	  <DependentUpon>GeneralSubSettingsPageView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\SettingsPages\ExportSubSettingsPageView.axaml.cs">
	  <DependentUpon>ExportSubSettingsPageView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\SettingsPages\VisualsSubSettingsPageView.axaml.cs">
	  <DependentUpon>VisualsSubSettingsPageView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\SettingsPages\UserDataSubSettingsPageView.axaml.cs">
	  <DependentUpon>UserDataSubSettingsPageView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\SettingsPages\AboutSubSettingsPageView.axaml.cs">
	  <DependentUpon>AboutSubSettingsPageView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\SettingsPageView.axaml.cs">
	  <DependentUpon>SettingsPageView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\ExportPageView.axaml.cs">
	  <DependentUpon>ExportPageView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\GraphPageView.axaml.cs">
	  <DependentUpon>GraphPageView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\ProjectPageView.axaml.cs">
	  <DependentUpon>ProjectPageView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\TimerPageView.axaml.cs">
	  <DependentUpon>TimerPageView.axaml</DependentUpon>
	</Compile>
	<Compile Update="Views\Pages\TaskDetailsPageView.axaml.cs">
	  <DependentUpon>TaskDetailsPageView.axaml</DependentUpon>
	</Compile>
  </ItemGroup>

  <ItemGroup>
	<EmbeddedResource Update="Properties\Resources.resx">
	  <Generator>ResXFileCodeGenerator</Generator>
	  <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	</EmbeddedResource>
  </ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
		<AvaloniaResource Include="Assets\Images\**" />
		<AvaloniaResource Include="Assets\Themes\**" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Assets\Images\haken-kreis.svg" />
	  <EmbeddedResource Include="Assets\Images\kalender-jahr.svg" />
	  <EmbeddedResource Include="Assets\Images\kalender-monat.svg" />
	  <EmbeddedResource Include="Assets\Images\kalender-tag.svg" />
	  <EmbeddedResource Include="Assets\Images\kalender-woche.svg" />
	  <EmbeddedResource Include="Assets\Images\kreuz.svg" />
	  <EmbeddedResource Include="Assets\Images\loeschen.svg" />
	  <EmbeddedResource Include="Assets\Images\pfeil-links.svg" />
	  <EmbeddedResource Include="Assets\Images\pfeil-oben.svg" />
	  <EmbeddedResource Include="Assets\Images\pfeil-rechts.svg" />
	  <EmbeddedResource Include="Assets\Images\pfeil-unten.svg" />
	  <EmbeddedResource Include="Assets\Images\stift.svg" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Assets\Fonts\AnyBody\" />
	</ItemGroup>

</Project>